### ISSUE TITLE
Can't scroll down when index larger than page-hight

### ISSUE THREAD

**Issue by JK742020** [humhub/humhub-modules-wiki#144]
I tried to make a glossar using the wiki. Every letter from A to Z is H1 and the topics listet are H2. I would like to use the index on the right side of the wiki to jump to the letter I am interested in. But I can not scroll down completely. Content area scrolls index not!

**Comment by Oremountainflorian** [comment]
Replicates https://github.com/humhub/humhub-modules-wiki/issues/92? 

@MasterMindNET claimed it's fixed with https://github.com/humhub/humhub-modules-wiki/pull/134, but in our wiki (1.3.15) with HumHub v1.6.4. it doesn't work yet. It still cut's some options as you can see here 

![grafik](https://user-images.githubusercontent.com/44228345/97861476-24d5d400-1d04-11eb-9041-e804eaf64c37.png)

**Comment by MasterMindNET** [comment]
The actual issue was that the main content page could be scrolled infinity (where no space). 

I have also added a scroll for the navigation, but this is not my failure, or at least at some part cause I may lack this.

I will take a look at this. 
but firstly I would like to know 
1. what is your resolution?
2. do you scroll in to see it? 
3. have all the changes been merged?

**Comment by Oremountainflorian** [comment]
Regarding navigation scroll: 

Screenshot above taken with 1920x1080. 

With 1366x768 I see less. Without any scrolling, I see:

![grafik](https://user-images.githubusercontent.com/44228345/97870855-db8d8080-1d13-11eb-906d-01855a2daa63.png)

When I scroll down the navigation bar also scrolls down but just until "Top bar" (where we find number members, the picture, ...) disappears from the screen. So I can never see the navigation points 13, 13.1, 13.2 and so on (as you can see in the post above with 1920x1080). 

![grafik](https://user-images.githubusercontent.com/44228345/97870994-1a233b00-1d14-11eb-8dd3-143787c8bab7.png)

**Comment by JK742020** [comment]
Exactly the same thing. Couldn't describe better as @Oremountainflorian

**Comment by buddh4** [comment]
https://github.com/humhub/humhub-modules-wiki/pull/134 was not merged yet, and needs some additional work in order not to kill the navigation scrolling. I'll have another look into the PR tomorrow.

**Comment by MasterMindNET** [comment]
Yep, @buddh4, thank you!
Because I have asked several questions ([here it is](https://github.com/humhub/humhub-modules-wiki/issues/144#issuecomment-720448221)) here and I have not received the answers to them

Thank you again!

**Comment by buddh4** [comment]
Fixed in https://github.com/humhub/humhub-modules-wiki/commit/8607437274f053275218345f651abb2ee098f35f
