### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by alexryans** [humhub/humhub-modules-wiki#45]
It would be great if there was some form of permissions within the Wiki, disallowing edit and write permissions to some members of a Space - for instance, only Admins could add and edit the Wiki.

Could be uncoupled from the main Space permissions, so the Space Owner and Admins could set permissions just for the Wiki module on a per-Space basis to each member of a Space.

E.G:

Space Owner - Full Access
Admin 1 - Full Access
Member 1 - Read Only Access
Member 2 - Read Only Access
Member 3 - Full Access

**Comment by buddha87** [comment]
Why not adding some members to the moderator group of the space ?
I would rather suggest adding the ability to add custom space groups instead of a user level permission.

**Comment by alexryans** [comment]
This may be a better solution, however for the time being, we are currently running version 0.20.1 of HumHub - is the moderator solution available in a higher version than this, or have I just completely missed it?

**Comment by buddha87** [comment]
yes, there is a new/enhanced permission system since V1.0.

I would suggest to update your installation to the latest stable verion 1.0.1 since your version is not supported anymore. Don't forget to make a backup ! Here is the update guide: https://www.humhub.org/docs/guide-admin-updating.html. Note that the updater module should not be used to update to v1.1 beta, some people had timeout issues while updating. We are currently working on the issue.

**Comment by alexryans** [comment]
Great, thanks for the clarification. We're looking at upgrading now.
